# Generated by Django 4.2.13 on 2024-06-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_image_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='name',
        ),
    ]
