# Generated by Django 4.2.13 on 2024-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pricing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='image',
            field=models.ImageField(default=2, upload_to='pricing/'),
            preserve_default=False,
        ),
    ]
